name: qubox CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ci"
  ci:
    name: qubox CI

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pytest
          pip install .
          
      - name: Test with pytest
        run: |
          pytest qubox/tests/test_maxcut.py
          pytest qubox/tests/test_nhot.py

      # - name: Check black
      #   run: black --check .

      # - name: Check isort
      #   run: isort --check-only .

      # - name: Check mypy
      #   run: mypy .
      
      # - name: Run Tests
      #   run: pytest tests/

      # This workflow uses actions that are not certified by GitHub.
      # They are provided by a third-party and are governed by
      # separate terms of service, privacy policy, and support
      # documentation.
      # - name: Publish qubox
      # - uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}